language: ruby
rvm:
- 2.2
#- 2.1
#- 2.0
- 1.9.3
env:
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.5.1
services:
- docker
script:
- wget -O- bit.ly/ansibletest | sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: MMkzGqAmpe9PKNxver7R1eJAi7yIG7/GUaQ4Dd5a5Wi3ETp1wivPAAgvqLCBh4Xi4O2y6LFHMdNUO5SfsN4O46p7tvlGVRpGF8Lg2euCKNGvp27b4dtYPVfZDZ+uYSDoBZFCzrEPdrV1/c3jEPKr1moRhgoxrPlxrJAi5rTaZpcMo389ceJBHVaia5q0/CkKk5o1pm5Xo4c68Fy04644lAeQHoqvchkjUNIK/pG0pIetdtIb8dmqiIb29FYplOdPOUavXmrwj11StZFYBjTx3oUn0qbDtKZYKpSEa/hNLGgkQV60Ww21WRRRrsCaCbg8CZ1ieja0AKNDwVNncHeSEEHErj2uO/StdWZpEYI33IreBVg19pe5hjUqwv96CLaIWjWW6WdXPTTD3Rndsul2ekucKm7VAeqBaEmx50prc7Ke2ctFqRULJDuVTj2UIRrBTxJ/jEYZE9BHaunEvYwSUvJ0CLOVZeC9fxPGyNAOnGC1O3J/r7O1iIu3TlKo6ZFfNdJhOxPUEf7TsAVKViqPce75aBnZesg2r/ht3lP4OLKEtSdYciuE/uGtLqM/OvJxWyb70OrneQXunx86uguCEYI8xHGKGS1PflQuutOwZzkHj/KAN1B9Khf5/mMaN1GEF16zg8vv8/BIWKJWa2VqTXSoj2NLdZuiOsGzNwueldg=
  email:
    recipients:
      secure: R5/HuBIcY4Re2BfwKK/4/aBBIgm3l7/8Lnj/QCV+3WiWhdyyxMiu2sW21ck7PB1lcjPJEKZQBR+yaBTngxchiDw5ILmCEtH4I2r6PJdydz9LvHGTUymX4zpxT7olEos+pSN7l22GKCc9vXAwXW1VX2tkJOUz4zIVsLgJcqad5tVYdu+GXlHU7XUOB+1i9iValr8F+ch7AZ5pp3h4ShKbN9rTDEHG6IpYsP5d5ZJHqSyLBo1msn1Zmu9E2AUZs65OlVPVoD0JyX9QsTj3yzpwfMoJSaB4QX0ttDh+OZE5PdtgFtNus5gVIn/cpM4rIiWa67oTMMYeH+FddexEijIqm8DXEyTWvneBnh01LpRfe/mGPpysYBBhtTrLF1hgax7HgY0A4RADi53AMH7U+Tn4G+yVO0Wdo515WQ3iMKLPYS9a41iNrlR1dia+9GSUSgOo+xRCE/u9srJ7WC9aB0STjkVTenj6piX/f2RWy3mErsVb78MlqQb/9TnQ0JK3ATiRtXi4UnX96GDDBhGDw2iT1CdjZBEVpF/6wbePVWd1hSnd84+v3ju/JIsLtckse5CbmFIFfhpHy/d8ZJTcZfYORy5yna8KbcagvrY6yxyM51yN/k/Zf7AEkqOsc8m1USpDGjxJ7orykpVrq51jCXKc9tQQkc65aog8IaciK0iRMN8=
