---
- name: add ondrej ppa key to apt-key
  apt_key: file=/root/ondrej_ppa.gpg
  sudo: yes

- name: ondrej sources.list
  template: >
    src=ondrej-php.list.j2
    dest=/etc/apt/sources.list.d/ondrej-php.list
    force=no
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes

- name: Install php5.6-fpm
  apt: name=php5.6-fpm
  sudo: yes
