---
- include: compat.yml
- include: get_key.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: fpm config file
  sudo: True
  template: >
    src=php-fpm.conf.j2
    dest=/etc/php/5.6/fpm/php-fpm.conf
  notify: restart php5.6-fpm

- name: config file dir, run dir
  sudo: True
  file:
    path: "{{item}}"
    state: directory
  with_items:
  - /etc/php/5.6/fpm/pool.d/
  - /run/php

- name: config file
  sudo: True
  template: >
    src=www.conf.j2
    dest=/etc/php/5.6/fpm/pool.d/www.conf
  notify: restart php5.6-fpm

- name: enable php5.6-fpm on boot
  sudo: yes
  service: name=php5.6-fpm enabled=yes

# workaround
# "msg": "no service or tool found for: php-fpm5.6"
# when we try to use state=started
- name: start php5.6-fpm
  command: /etc/init.d/php5.6-fpm start
  register: start_result
  sudo: yes
  changed_when: "'already running' not in start_result.stderr and '' != start_result.stderr"
  failed_when: False
